#!/usr/bin/env php
<?php

require __DIR__ . "/config/constants.php";
require_once NOVA_VENDOR_PATH.'/autoload.php';

if (php_sapi_name() === "cli") {
    if (class_exists("Dotenv\Dotenv") && file_exists(NOVA_BASE_PATH . "/.env")) {
        $dotenv = \Dotenv\Dotenv::createImmutable(NOVA_BASE_PATH);
        $dotenv->load();
        if (!empty(getenv("BASE_FOLDER"))) {
            $_ENV["BASE_FOLDER"] = getenv("BASE_FOLDER");
        }
    }
    $appType  = "console";
    $app      = require NOVA_LIBRARY_PATH . "/bootstrap/bootstrap.php";
    $exitCode = $app->run();
} else {
    $exitCode = 1;
}
exit($exitCode);